# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9677d6abdae07ffd938ad0a204077e5bd77fb73c145af5ae7dba7ba506c7be3c7fedd526d9c6544fd0008096c89b002bc07692e6b3925f2f75476b2f492857

test:
  secret_key_base: ef1d5f82eed24b0f6b4920b3bbb4f68065e3381a9d4b4f5afdbc0e549e88ddfcefaef3aa96d92813517a5922b85f3247269221a8596ccd187932e4c6567cdbc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
